spring.application.name=contentieux-security

# --- Server ---
server.port=8098

# --- Thymeleaf DÉSACTIVÉ (migration Angular) ---
spring.thymeleaf.enabled=false

# --- JWT Resource Server uniquement (pas besoin d'OAuth2 Client pour une API REST) ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/contentieux-realm

# --- Database ---
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/contentieux_db12?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# --- Keycloak Admin ---
keycloak.admin.server-url=http://127.0.0.1:8080
keycloak.admin.realm=master
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli

# --- Target Realm ---
keycloak.target.realm=contentieux-realm

# --- Upload ---

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB



# Configuration SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jablounomaima2@gmail.com
spring.mail.password=szzl rxrw jura abaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.upload.dir=./uploads